# Generated by Django 5.2.7 on 2026-02-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bloodbank_contact_number_bloodbank_is_24_7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='citizenship_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='district',
            field=models.CharField(default='Kathmandu', max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
