# Generated by Django 5.2.7 on 2026-02-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bloodbank_latitude_bloodbank_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
