# Generated by Django 5.2.7 on 2026-02-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bloodrequest_latitude_bloodrequest_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodbank',
            name='total_capacity',
            field=models.IntegerField(default=1000),
        ),
    ]
