# Generated by Django 5.2.7 on 2026-02-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bloodrequest_user_donor_user_donationevent_feedback_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
