# Generated by Django 5.2.7 on 2026-02-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_message_attachment_message_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blood_requests/'),
        ),
    ]
