# Generated by Django 5.2.7 on 2026-02-19 04:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_bloodrequest_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hospital_name', models.CharField(blank=True, max_length=255, null=True)),
                ('report_file', models.FileField(upload_to='health_reports/')),
                ('description', models.TextField(blank=True, null=True)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('next_test_date', models.DateField(blank=True, null=True)),
                ('allow_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
