# Generated by Django 5.2.7 on 2026-02-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_healthreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinerecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vaccine_photos/'),
        ),
    ]
