# Generated by Django 5.2.7 on 2026-02-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_vaccinerecord_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
